submodule_add:
	git submodule add git@gist.github.com:6426fb2014ad9ede5bc2dd26f49c33fc.git __tests__/compose
	git submodule add git@gist.github.com:d68c0b11db9607694425f40172c1095a.git __tests__/reduce
	git submodule add git@gist.github.com:e8f10023666141899f0d71989afb82f6.git __tests__/map
